font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        14.0
window_padding_width 8
background_opacity 0.95
confirm_os_window_close 0
# Crear splits
map cmd+d launch --location=vsplit --cwd=current
map cmd+shift+d launch --location=hsplit --cwd=current

# Navegar entre splits
map cmd+j neighboring_window down
map cmd+k neighboring_window up
map cmd+h neighboring_window left
map cmd+l neighboring_window right

# Cerrar ventana actual
map cmd+w close_window
map cmd+t new_tab
map cmd+shift+] next_tab
map cmd+shift+[ previous_tab
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
scrollback_lines 10000
shell_integration enabled
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard



# BEGIN_KITTY_THEME
# Atelier Sulphurpool Dark
include current-theme.conf
# END_KITTY_THEME
